import Head from "next/head";
import styles from "../styles/Home.module.css";
import Products from "./Products";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>LocalStorage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Products />
    </div>
  );
}
